name: pypi-release

on:
  release:
    types: [published]

jobs:
  deploy:
    strategy:
      matrix:
        os: ['ubuntu-latest']
        python-version: [3.10]

    runs-on: ${{ matrix.os }}
    environment: 
      name: Release-PyPi
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Build
        run: |
          pip install twine
          python setup.py sdist bdist_wheel

      - name: Check wheels
        run: twine check dist/*

      - name: Upload to TestPyPi
        uses: pypa/gh-action-pypi-publish@v1.6.4
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/

      - name: Upload to PyPi
        uses: pypa/gh-action-pypi-publish@v1.6.4
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
