name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  python-unit-test:
    container:
      image: python:3.8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        shell: bash
        run: |
          pip install .[dev]
          python -m pytest tests/